name: cloud-id
channels:
  - conda-forge
dependencies:
  - cartopy=0.17.0
  - geopy=1.17.0
  - h5py=2.8.0
  - matplotlib=2.2.2
  - numpy=1.16.2
  - pandas=0.23.4
  - pyhdf=0.9.0
  - python=3.6
  - requests=2.20.0
  - tqdm=4.28.1
  - ordered-set=3.1.1
  - pip:
    - scikit_learn==0.20.2
    - tensorflow==1.12.0
    - git+https://github.com/trz228/tflearn.git
    - git+https://github.com/trz228/satpy.git